spring:
  data:
    mongodb:
      authentication-database: admin
      username: ssafyNoHack
      password: D204ssafyNoHack
      database: ssafy
      port: 37017
      host: k7d204.p.ssafy.io

  datasource:
    url: jdbc:mysql://k7d204.p.ssafy.io:33306/ssafy?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ssafyNoHack
    password: D204ssafyNoHack
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: '837411735395-3m079fdsp3l17j3udu4sdm03kge4kts7.apps.googleusercontent.com'
            clientSecret: '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'
            redirectUri: "https://k7d204.p.ssafy.io/api/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          naver:
            clientId: 'S5fwB7DJ8aOXYHNj4cEh'
            clientSecret: 'ehH3zm_h9U'
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "https://k7d204.p.ssafy.io/api/oauth2/callback/{registrationId}"
            scope:
              - nickname
              - email
            clientName: Naver
          kakao:
            clientId: '52ab9c24f079107897220e2677d5a782'
            clientSecret: '9F22srrcwNw2wjvwE4fvdX2JSRjAqPyO'
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "https://k7d204.p.ssafy.io/api/oauth2/callback/{registrationId}"
            scope:
              - profile_nickname
              - account_email
            clientName: Kakao

        # Provider ??
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000/*, http://localhost:8443/*
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - https://k7d204.p.ssafy.io/myPage/myPageTest

server:
  port: 8443
  servlet:
    context-path: /api
